"""
Recommendation Builder.

Compose the complete Decision Intelligence pipeline into a single
Recommendation object.
"""

from core.analyzer import Analyzer
from core.provider_router import ProviderRouter
from core.ranking_engine import RankingEngine
from core.scoring import ScoringEngine
from core.strategy_engine import StrategyEngine

from domain import Recommendation, TaskRequest


class RecommendationBuilder:
    """
    Build a Recommendation from a TaskRequest.
    """

    def __init__(self) -> None:
        self.analyzer = Analyzer()
        self.strategy_engine = StrategyEngine()
        self.scoring_engine = ScoringEngine()
        self.ranking_engine = RankingEngine()
        self.provider_router = ProviderRouter()

    def build(
        self,
        request: TaskRequest,
    ) -> Recommendation:
        """
        Execute the complete Decision Intelligence pipeline.
        """

        # Analyze the incoming task.
        profile = self.analyzer.analyze(request)

        # Select the execution strategy.
        strategy = self.strategy_engine.recommend(profile)

        # Score every available model.
        scores = self.scoring_engine.score_models(profile)

        # Convert scores into ranked recommendations.
        ranking = self.ranking_engine.build(
            profile,
            scores,
        )

        # Select the highest-ranked model.
        best = self.ranking_engine.best(ranking)

        recommendation = Recommendation(
            strategy=strategy,
            provider=best.provider,
            recommended_model=best.model,

            # Current MVP executes through Qwen.
            execution_provider="qwen",
            execution_model="qwen-plus",

            estimated_cost=best.estimated_cost,
            estimated_latency_ms=best.estimated_latency_ms,
            confidence=0.90,

            reason="Recommendation generated by the Decision Intelligence pipeline.",

            ranking=ranking,
        )

        # Resolve the execution backend.
        self.provider_router.resolve(
            recommendation,
        )

        return recommendation