"""
Recommendation Builder.

Compose the complete Decision Intelligence pipeline into a single
Recommendation object.
"""

from core.analyzer import Analyzer
from core.ranking_engine import RankingEngine
from core.scoring import ScoringEngine
from core.strategy_engine import StrategyEngine

from domain import Recommendation, TaskRequest


class RecommendationBuilder:
    """
    Build a Recommendation from a TaskRequest.
    """

    def __init__(self) -> None:
        self.analyzer = Analyzer()
        self.strategy_engine = StrategyEngine()
        self.scoring_engine = ScoringEngine()
        self.ranking_engine = RankingEngine()

    def build(
        self,
        request: TaskRequest,
    ) -> Recommendation:
        """
        Execute the complete Decision Intelligence pipeline.
        """

        return self.build_with_details(request)[0]

    def build_with_details(
        self,
        request: TaskRequest,
    ) -> tuple[Recommendation, object, list]:
        """Build a recommendation with analysis artifacts for response explainability."""

        profile = self.analyzer.analyze(request)

        # Select the recommended strategy.
        strategy = self.strategy_engine.recommend(profile)

        # Score every available model.
        scores = self.scoring_engine.score_models(profile)

        # Convert scores into ranked recommendations.
        ranking = self.ranking_engine.build(
            profile,
            scores,
        )

        # Select the highest-ranked model.
        best = self.ranking_engine.best(ranking)

        recommendation = Recommendation(
            strategy=strategy,
            provider=best.provider,
            recommended_model=best.model,

            estimated_cost=best.estimated_cost,
            estimated_latency_ms=best.estimated_latency_ms,
            confidence=0.90,

            reason="Recommendation generated by the Decision Intelligence pipeline.",

            ranking=ranking,
        )

        return recommendation, profile, scores
